kind: Service
apiVersion: v1
metadata:
  name: devctr
spec:
  type: NodePort
  selector:
    app: devctr
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: devctr
  labels:
    app: devctr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devctr
  template:
    metadata:
      labels:
        app: devctr
    spec:
      containers:
      - name: container1
        image: gcr.io/google-samples/hello-app:2.0
        ports:
        - containerPort: 8080
